/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rtspclienttestapp_RTSPClient */

#ifndef _Included_com_example_rtspclienttestapp_RTSPClient
#define _Included_com_example_rtspclienttestapp_RTSPClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rtspclienttestapp_RTSPClient
 * Method:    openURL
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_rtspclienttestapp_RTSPClient_openURL
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_example_rtspclienttestapp_RTSPClient
 * Method:    playURL
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_rtspclienttestapp_RTSPClient_playURL
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_rtspclienttestapp_RTSPClient
 * Method:    closeURL
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_rtspclienttestapp_RTSPClient_closeURL
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
